name: CI

on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Run app (smoke)
        run: ./build/src/RigaMagician

      - name: Test
        run: ctest --test-dir build --output-on-failure --verbose
